# Generated by Django 4.0.3 on 2022-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('DI', 'Директор'), ('AD', 'Администратор'), ('CO', 'Повар'), ('CA', 'Кассир'), ('CL', 'Уборщик')], default='CA', max_length=2),
        ),
    ]
